[package]
name = "mojaloop-api"
version = "0.1.0"
authors = ["msk- <mattkingston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# fspiox-api = { git = "https://github.com/partiallyordered/fspiox-api", rev = "3925874e3791653c8f57bd7ad20f8ac748e9050e" }
fspiox-api = { path = "/home/msk/projects/github.com/msk-/fspiox-api/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
derive_more = "0.99"

# Optional
reqwest = { version = "0.11", optional = true, default-features = false, features = ["json", "blocking"] }

[features]
default = []
