name: Build

on:
  push:
    branches:
    - '**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: cargo b --all-features
    # At the time of writing, cargo test only generates typescript types.
    - run: cargo t --all-features
